---
title: "Budget Case Study"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tm)
library(syuzhet)
library(ggplot2)
library(wordcloud)
library(tuber) # youtube API
library(magrittr) # Pipes %>%, %T>% and equals(), extract().
library(tidyverse) # all tidyverse packages
library(purrr) # package for iterating/extracting data

```

Column {data-width=450}
-----------------------------------------------------------------------

### Chart A

```{r}

client_id <- "375771870105-dlhu23ucu0r42qc029v0a9jhkjabaqml.apps.googleusercontent.com"
client_secret <- "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"

# use the youtube oauth 
yt_oauth(app_id = client_id,
         app_secret = client_secret,token= '')

data1= get_all_comments(video_id="Se28XHI2_xE")

b<-write.csv(data1,file="T5.csv",row.names=FALSE)
a<-read.csv("D:/Class files/Module 3/INTM577(BA2)/T5.csv")

##### tm ####
library(tm)

corpus = iconv(a$textDisplay, "latin1", "UTF-8")
corpus<- Corpus(VectorSource(corpus))

toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))
docs=corpus
docs <- tm_map(docs, toSpace, "/")
docs <- tm_map(docs, toSpace, "@")
docs <- tm_map(docs, toSpace, "\\|")
corpus=docs
corpus<- tm_map(corpus,tolower)
corpus<-tm_map(corpus,removePunctuation)# remove puntuations like , .
corpus<- tm_map(corpus,removeNumbers)
cleanset<-tm_map(corpus,removeWords,stopwords('english'))# remove common words
removeURL<- function(x)gsub('http[[:alnum:]]=','',x)
cleanset<-tm_map(cleanset,content_transformer(removeURL))
x=cleanset


tdm<-TermDocumentMatrix(cleanset)
tdm # display information


```

Column {.tabset}
-----------------------------------------------------------------------

### Sentimental analysis

```{r}
tdm<-as.matrix(tdm)
v=sort(rowSums(tdm))

library(wordcloud)
w<-data.frame(names(v),v)

colnames(w)<-c('word','freq')
set.seed(1234)
wordcloud(words=w$word,freq=w$freq)


write.csv(tdm,"tdm.csv")
#### sentimental analysis #####
library(syuzhet)
data=read.csv("tdm.csv")
mysentiment_tech<-get_nrc_sentiment(data$X)


```

### Visualization

```{r}
#calculationg total score for each sentiment
Sentimentscores_tech<-data.frame(colSums(mysentiment_tech[,]))
names(Sentimentscores_tech)<-"Score"
Sentimentscores_tech<-cbind("sentiment"=rownames(Sentimentscores_tech),Sentimentscores_tech)
rownames(Sentimentscores_tech)<-NULL
Sentimentscores_tech_r=Sentimentscores_tech
#*************************************************************************************
library(ggplot2)
ggplot(data=Sentimentscores_tech,aes(x=sentiment,y=Score))+
  geom_bar(aes(fill=sentiment),stat = "identity")+
  theme(legend.position="none")+
  xlab("Sentiments")+ylab("scores")+ggtitle("R Program")




```

### High frequency

```{R}

tail(w,n=5)

```





